version: 1.2
workflows:
  - name: filterbranch
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    filters:
      branches:
        - /develop/
  - name: filtertag
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    filters:
      tags:
        - 1.0
  - name: filtermulti
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    filters:
      branches:
        - dev*
      tags:
        - /1\.\d+/
  - name: filternone
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    authors:
      - name: Denis Yuen
        orcid: 0000-0002-6130-1021
      - name: Gregory Hogue
        email: gfjhogue@gmail.com
        role: Software Developer
        affiliation: OICR
      - name: Just Name
      - name: Just Orcid
        orcid: 0000-0000-0000-0000
  - name: filterregexerror
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    filters:
      branches:
        - /[/
